RDKCOM-4442: REFPLTB-2604 : CCsp-common-library compilation issue in kirkstone
Reason for change: In Kirkstone build, faced below issues after removing the Werror=array-bounds flag
(i)  CcspCommonLibrary/source/util_api/slap/components/SlapVarConverter/slap_vco_stringto.c:1242:9: error: array subscript 'long unsigned int[0]' is partly outside array bounds of 'UCHAR[4]' {aka 'unsigned char[4]'} [-Werror=array-bounds]
|  1242 |         *(PULONG)tempValue = 0;
|       |         ^~~~~~~~~~~~~~~~~~
| ../../../../../../../../../../../../rdkb/components/opensource/ccsp/CcspCommonLibrary/source/util_api/slap/components/SlapVarConverter/slap_vco_stringto.c:1232:37: note: while referencing 'tempValue'
|  1232 |     UCHAR                           tempValue[4];
(ii) CcspCommonLibrary/source/cosa/include/ansc_wrapper_base.h:277:53: error: array subscript 'long unsigned int[0]' is partly outside array bounds of 'UCHAR[4]' {aka 'unsigned char[4]'} [-Werror=array-bounds]
|   277 |     #define  AnscUlongFromNToH                      AnscSwapUlong
| ../../../../../../../../../../../../rdkb/components/opensource/ccsp/CcspCommonLibrary/source/util_api/slap/components/SlapVarConverter/slap_vco_stringto.c:1271:13: note: in expansion of macro 'AnscUlongFromNToH'
|  1271 |     return  AnscUlongFromNToH(*(PULONG)tempValue);
(iii) CcspCommonLibrary/source/cosa/include/ansc_wrapper_base.h:478:49: error: array subscript 'long unsigned int[0]' is partly outside array bounds of 'CHAR[5]' {aka 'char[5]'} [-Werror=array-bounds]
|   478 |     #define  AnscWriteUlong(addr, data)         *(PULONG )(addr) = data
|       |                                                 ^~~~~~~~~~~~~~~~
| ../../../../../../../../../../../../rdkb/components/opensource/ccsp/CcspCommonLibrary/source/util_api/asn.1/components/asn1_basic/ansc_asn1_integer.c:1031:13: note: in expansion of macro 'AnscWriteUlong'
|  1031 |             AnscWriteUlong(pTmp, AnscUlongFromHToN(ulResult));
|       |             ^~~~~~~~~~~~~~
(iv) CcspCommonLibrary/source/util_api/ansc/AnscCrypto/ansc_crypto_random.c:125:5: error: array subscript 'long unsigned int[1]' is partly outside array bounds of 'char[16]' [-Werror=array-bounds]
|   125 |     *(PULONG)&hashString[12] = (ULONG)hashString;
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~
(v) CcspCommonLibrary/source/util_api/ansc/AnscCrypto/ansc_crypto_random.c:178:5: error: array subscript 'long unsigned int[1]' is partly outside array bounds of 'char[16]' [-Werror=array-bounds]
|   178 |     *(PULONG)&hashString[12] = (ULONG)hashString;
Test Procedure: 1. Verified that it is not affecting dunfell build.
                2. bitbake ccsp-common-library
Risks: None
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>
Priority: P1

(cherry picked from commit b195ebbc84e20038a12165d0fde61d19d9a8f80b)
Change-Id: I24ce3ab45604aa8a2793fa81cc8b306bb36a3313