REFPLTB-2678 : Ccsp-common-library do_compile issue with RDK_LOG_INFO in feature branch
Reason for change :
1 . ../../../../../../../../../rdkb/components/opensource/ccsp/CcspCommonLibrary/source/debug_api/ansc_debug.c:158:17: error: 'RDK_LOG_INFO' undeclared (first use in this function); did you mean 'LOG_INFO'?
|   158 |     int level = RDK_LOG_INFO;
|       |                 ^~~~~~~~~~~~
|       |                 LOG_INFO

2 below issue caused in rpi4-64
 . /rdkb/components/opensource/ccsp/CcspCommonLibrary/source/cosa/package/cli/include/scli_shell_definitions.h:116:53: error: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]
|   116 | #define  SCLI_LOCAL_TEMP_FILE_TEMPLATE              "/tmp/sh_cout_%u"
|       |                                                     ^~~~~~~~~~~~~~~~~

3 below issue caused in rpi4-32 , if we changed %u to %lu

../../../../../../../../../../../../../rdkb/components/opensource/ccsp/CcspCommonLibrary/source/cosa/package/cli/include/scli_shell_definitions.h:116:53: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Werror=format=]
|   116 | #define  SCLI_LOCAL_TEMP_FILE_TEMPLATE              "/tmp/sh_cout_%lu"
|       |                                                     ^~~~~~

Added the required header file which defines the RDK_LOG_INFO function
And changed format specifier for rpi4-64 and made (ULONG)pSession for
both builds

Test Procedure: 1. Verified that it is not affecting dunfell build.
                2. bitbake ccsp-common-library
Risks: Low

Change-Id: I06ca9f8f94b5b90bdb121e956ce5253eb31db17e
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>